version: "2"
services:
  ftp:
    build: .
    container_name: ftp
    image: livingstoneonline/ftp
    restart: always
    environment:
      - FTP_IP=192.168.99.100
    volumes:
      - "./ftp:/srv/ftp"
    ports:
      - "20-21:20-21"
      - "21100-21110:21100-21110"
